name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        sudo apt install -y perl
        sudo cpan install Switch JSON File::Which Config::Simple
        perl nipe.pl install -f
        perl nipe.pl status